services:
  - type: web
    name: project-scaffolder-api
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails db:migrate && bundle exec rails db:seed
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
